// <auto-generated />
using System;
using BTCPayServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BTCPayServer.Plugins.ProsusPay
{
    [DbContext(typeof(ProsusPayDbContext))]
    partial class TestPluginDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "1.1.0");

            modelBuilder.Entity("BTCPayServer.Plugins.ProsusPay.ProsusPayPayments", b =>
                {
                    b.Property<string>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("Created").HasColumnType("TEXT");
                    b.Property<string>("CryptoCode").HasColumnType("TEXT");
                    b.Property<decimal>("CryptoAmount").HasColumnType("DECIMAL");
                    b.Property<decimal>("FeeRate").HasColumnType("DECIMAL");
                    b.Property<decimal>("NetworkFee").HasColumnType("DECIMAL");
                    b.Property<string>("DestinationAddress").HasColumnType("TEXT");
                    b.Property<string>("SourceAddress").HasColumnType("TEXT");
                    b.Property<string>("TransactionId").HasColumnType("TEXT");
                    b.Property<decimal>("OriginalPaymentAmount").HasColumnType("DECIMAL");
                    b.Property<decimal>("OriginalNetworkPaymentFeeAmount").HasColumnType("DECIMAL");
                    b.Property<string>("OriginalTransactionId").HasColumnType("TEXT");
                    b.Property<string>("Status").HasColumnType("TEXT");
                    
                    b.Property<string>("StoreDataId").HasColumnType("TEXT");
                    b.Property<string>("PayoutDataId").HasColumnType("TEXT");
                    b.Property<string>("OriginalPaymentDataId").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProsusPayPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
